### ISSUE TITLE
UIStackView margins

### ISSUE THREAD

**Issue by Omarbasaleh** [sakiyamaK/DeclarativeUIKit#140]
You may add support to `directionalLayoutMargins` of `UIStackView`. So we can use the build in support of margins instead of using extra views when we use `padding()`.
```
extension UIStackView {
    @discardableResult
    func directionalLayoutMargins(_ margins: NSDirectionalEdgeInsets) -> Self {
        self.isLayoutMarginsRelativeArrangement = true
        self.directionalLayoutMargins = margins
        return self
    }
}
```

**Comment by sakiyamaK** [comment]
Thank you.
I'll get right on with the modifications.
The isLayoutMarginsRelativeArrangement is a UIStackView parameter, but the directionalLayoutMargins is a UIView parameter, so I'll extend it to each.

**Comment by sakiyamaK** [comment]
add some functions

```
extension UIStackView {
    @discardableResult
    func margins(_ margins: NSDirectionalEdgeInsets) -> Self {
        self.isLayoutMarginsRelativeArrangement(true).directionalLayoutMargins(margins)
    }
}
```

**Comment by sakiyamaK** [comment]
https://github.com/sakiyamaK/DeclarativeUIKit/releases/tag/3.2.0
