### ISSUE TITLE
Readmeの英語が変

### ISSUE THREAD

**Issue by hameji** [sakiyamaK/DeclarativeUIKit#66]
> CocoaPods
>[CocoaPods](https://cocoapods.org/) is a dependency manager for Cocoa projects. For usage and installation instructions, visit their website. To integrate Alamofire into your Xcode project using CocoaPods, specify it in your Podfile:

なぜか「CocoaPodsを使用し、**Alamofire**をあなたのXcode projectに統合するためには、、、」

って英語の文になっている。

**Comment by hameji** [comment]
Swift Package Manager のとこにも

> To install IQKeyboardManager package via Xcode

なぜか、IQKeyboardManager のパッケージをXcode経由でインストールするにはとなっている。

**Comment by hameji** [comment]
@sakiyamaK 気付いてなければ👏

**Comment by sakiyamaK** [comment]
@hameji 
そこのプロジェクトの文言をコピペしたせいですねw
ありがとうございます、直します
